# Generated by Django 6.0.2 on 2026-02-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='duration_seconds',
            field=models.IntegerField(default=30),
        ),
    ]
