# Generated by Django 6.0.2 on 2026-02-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='NONE', max_length=10),
        ),
    ]
