# Generated by Django 6.0.2 on 2026-04-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_scoring_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='lifecycle_state',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='outlier_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timer_invalidated',
            field=models.BooleanField(default=False),
        ),
    ]
