# Generated by Django 6.0.2 on 2026-02-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_server'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='active_competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_server', to='competitions.competition'),
        ),
    ]
