FROM python:3.12-slim

WORKDIR /usr/local/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY VieBackend /usr/local/app/

EXPOSE 8000

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "VieBackend.asgi:application"]
