# Generated by Django 6.0.2 on 2026-04-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='best_weekly_personal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_weekly_goal_points',
            field=models.IntegerField(default=120),
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('competitive_points', models.IntegerField(default=0)),
                ('personal_points', models.IntegerField(default=0)),
                ('weekly_goal_points', models.IntegerField(default=120)),
                ('reached_goal_at', models.DateTimeField(blank=True, null=True)),
                ('low_full_count', models.IntegerField(default=0)),
                ('medium_full_count', models.IntegerField(default=0)),
                ('high_full_count', models.IntegerField(default=0)),
                ('low_reduced_count', models.IntegerField(default=0)),
                ('medium_reduced_count', models.IntegerField(default=0)),
                ('high_reduced_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
